// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tracker.ConfigurationService.Infrastructure;

#nullable disable

namespace Tracker.ConfigurationService.Infrastructure.Migrations
{
    [DbContext(typeof(TrackerConfigurationDbContext))]
    [Migration("20260329113000_AddPasskeyIdentity")]
    partial class AddPasskeyIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
