// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tracker.ConfigurationService.Infrastructure;

#nullable disable

namespace Tracker.ConfigurationService.Infrastructure.Migrations
{
    [DbContext(typeof(TrackerConfigurationDbContext))]
    [Migration("20260329003756_AddTrackerNodeConfigurations")]
    partial class AddTrackerNodeConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.AuditRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_role");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.BanRuleEntity", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("Scope", "Subject");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("bans", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.MaintenanceRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.ToTable("maintenance_runs", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.PasskeyCredentialEntity", b =>
                {
                    b.Property<string>("Passkey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("passkey");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Passkey");

                    b.HasIndex("UserId");

                    b.ToTable("passkeys", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.TorrentConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_hash");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .IsUnique();

                    b.ToTable("torrents", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.TorrentPolicyEntity", b =>
                {
                    b.Property<Guid>("TorrentId")
                        .HasColumnType("uuid")
                        .HasColumnName("torrent_id");

                    b.Property<bool>("AllowScrape")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_scrape");

                    b.Property<int>("AnnounceIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("announce_interval_seconds");

                    b.Property<int>("DefaultNumWant")
                        .HasColumnType("integer")
                        .HasColumnName("default_numwant");

                    b.Property<int>("MaxNumWant")
                        .HasColumnType("integer")
                        .HasColumnName("max_numwant");

                    b.Property<int>("MinAnnounceIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("min_announce_interval_seconds");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("WarningMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("warning_message");

                    b.HasKey("TorrentId");

                    b.ToTable("torrent_policies", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.TrackerNodeConfigurationEntity", b =>
                {
                    b.Property<string>("NodeKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_key");

                    b.Property<string>("ApplyMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("apply_mode");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_restart");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("NodeKey");

                    b.ToTable("tracker_node_configurations", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.UserPermissionEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("CanLeech")
                        .HasColumnType("boolean")
                        .HasColumnName("can_leech");

                    b.Property<bool>("CanScrape")
                        .HasColumnType("boolean")
                        .HasColumnName("can_scrape");

                    b.Property<bool>("CanSeed")
                        .HasColumnType("boolean")
                        .HasColumnName("can_seed");

                    b.Property<bool>("CanUsePrivateTracker")
                        .HasColumnType("boolean")
                        .HasColumnName("can_use_private_tracker");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("UserId");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.TorrentPolicyEntity", b =>
                {
                    b.HasOne("Tracker.ConfigurationService.Infrastructure.TorrentConfigurationEntity", "Torrent")
                        .WithOne("Policy")
                        .HasForeignKey("Tracker.ConfigurationService.Infrastructure.TorrentPolicyEntity", "TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("Tracker.ConfigurationService.Infrastructure.TorrentConfigurationEntity", b =>
                {
                    b.Navigation("Policy");
                });
#pragma warning restore 612, 618
        }
    }
}
