//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("BeeTracker.Serialization.BEncoding")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Verify")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+67843ed378c7dc1d0bb185312870b148db6d1187")]
[assembly: System.Reflection.AssemblyProductAttribute("BeeTracker.Serialization.BEncoding")]
[assembly: System.Reflection.AssemblyTitleAttribute("BeeTracker.Serialization.BEncoding")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Vygenerované třídou WriteCodeFragment nástroje MSBuild

